steps:
- dir: game
  name: gcr.io/cloud-builders/gcloud
  entrypoint: python3
  args: [cloud_deploy.py, $PROJECT_ID, function, europe-west1, '5000', '0']

- dir: game
  name: gcr.io/cloud-builders/gcloud
  entrypoint: python3
  args: [cloud_deploy.py, $PROJECT_ID, function, europe-west1, '5001', '0']

- dir: game
  name: gcr.io/cloud-builders/gcloud
  entrypoint: python3
  args: [cloud_deploy.py, $PROJECT_ID, function, europe-west1, '5002', '0']

- dir: game
  name: gcr.io/cloud-builders/gcloud
  entrypoint: python3
  args: [cloud_deploy.py, $PROJECT_ID, function, europe-west1, '5003', '0']

- dir: game
  name: gcr.io/cloud-builders/gcloud
  entrypoint: python3
  args: [cloud_deploy.py, $PROJECT_ID, function, europe-west1, '5004', '0']

- dir: game
  name: gcr.io/cloud-builders/gcloud
  entrypoint: python3
  args: [cloud_deploy.py, $PROJECT_ID, function, europe-west1, '5005', '0']

- dir: game
  name: gcr.io/cloud-builders/gcloud
  entrypoint: python3
  args: [cloud_deploy.py, $PROJECT_ID, function, europe-west1, '5006', '0']

- dir: game
  name: gcr.io/cloud-builders/gcloud
  entrypoint: python3
  args: [cloud_deploy.py, $PROJECT_ID, function, europe-west1, '5007', '0']

- dir: game
  name: gcr.io/cloud-builders/gcloud
  entrypoint: python3
  args: [cloud_deploy.py, $PROJECT_ID, function, europe-west1, '5008', '0']

timeout: 1200s
