steps:
- dir: web
  name: gcr.io/cloud-builders/docker
  args: [build, -t, europe-west1-docker.pkg.dev/$PROJECT_ID/from-dockerfile/web_image, .]

- name: gcr.io/cloud-builders/docker
  args: [push, europe-west1-docker.pkg.dev/$PROJECT_ID/from-dockerfile/web_image]

- name: gcr.io/cloud-builders/gcloud
  args:
  - run
  - deploy
  - web
  - --project
  - $PROJECT_ID
  - --region
  - europe-west1
  - --image
  - europe-west1-docker.pkg.dev/$PROJECT_ID/from-dockerfile/web_image
  - --set-env-vars
  - PROJECT_ID=$PROJECT_ID
