steps:
- args:
  - start
  entrypoint: echo
  id: start
  name: gcr.io/cloud-builders/gcloud
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5000'
  - '0'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5001'
  - '15'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5002'
  - '25'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5003'
  - '35'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5004'
  - '45'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5005'
  - '55'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5006'
  - '65'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5007'
  - '75'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5008'
  - '85'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
