steps:
- args:
  - start
  entrypoint: echo
  id: start
  name: gcr.io/cloud-builders/gcloud
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5000'
  - '0'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5001'
  - '20'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5002'
  - '40'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5003'
  - '60'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5004'
  - '80'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5005'
  - '100'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5006'
  - '120'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5007'
  - '140'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5008'
  - '160'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
