steps:
- args:
  - start
  entrypoint: echo
  id: start
  name: gcr.io/cloud-builders/gcloud
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5000'
  - '0'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5001'
  - '30'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5002'
  - '60'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5003'
  - '90'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5004'
  - '120'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5005'
  - '150'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5006'
  - '180'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5007'
  - '210'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
- args:
  - cloud_deploy.py
  - --project_id
  - $PROJECT_ID
  - function
  - europe-west1
  - '5008'
  - '240'
  dir: game
  entrypoint: python3
  name: gcr.io/cloud-builders/gcloud
  waitFor:
    - start
