steps:
- args:
  - run
  - web
  - --project
  - $PROJECT_ID
  - --region
  - europe-west1
  - --image
  - europe-west1-docker.pkg.dev/$PROJECT_ID/from-dockerfile/web_image
  - --set-env-vars
  - PROJECT_ID=$PROJECT_ID
  name: gcr.io/cloud-builders/gcloud
