steps:
- args:
  - builds
  - submit
  - .
  - --config
  - cloudbuild/sub_run_tests_1.yaml
  - --region
  - europe-west1
  - --gcs-source-staging-dir
  - gs://cloudbuild-$PROJECT_ID/source
  - --async
  - --substitutions
  - _BUCKET_DIR_NAME=$BUILD_ID
  entrypoint: gcloud
  name: gcr.io/cloud-builders/gcloud
- args:
  - builds
  - submit
  - .
  - --config
  - cloudbuild/sub_run_tests_2.yaml
  - --region
  - europe-west1
  - --gcs-source-staging-dir
  - gs://cloudbuild-$PROJECT_ID/source
  - --async
  - --substitutions
  - _BUCKET_DIR_NAME=$BUILD_ID
  entrypoint: gcloud
  name: gcr.io/cloud-builders/gcloud
- args:
  - builds
  - submit
  - .
  - --config
  - cloudbuild/sub_run_tests_3.yaml
  - --region
  - europe-west1
  - --gcs-source-staging-dir
  - gs://cloudbuild-$PROJECT_ID/source
  - --async
  - --substitutions
  - _BUCKET_DIR_NAME=$BUILD_ID
  entrypoint: gcloud
  name: gcr.io/cloud-builders/gcloud
- args:
  - builds
  - submit
  - .
  - --config
  - cloudbuild/sub_run_tests_4.yaml
  - --region
  - europe-west1
  - --gcs-source-staging-dir
  - gs://cloudbuild-$PROJECT_ID/source
  - --async
  - --substitutions
  - _BUCKET_DIR_NAME=$BUILD_ID
  entrypoint: gcloud
  name: gcr.io/cloud-builders/gcloud
- args:
  - run.py
  - $PROJECT_ID
  - tests-$PROJECT_ID
  - $BUILD_ID
  - wait_end
  - '1'
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/from-dockerfile/tests_image
- args:
  - run.py
  - $PROJECT_ID
  - tests-$PROJECT_ID
  - $BUILD_ID
  - write_stats
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/from-dockerfile/tests_image
- args:
  - run.py
  - $PROJECT_ID
  - tests-$PROJECT_ID
  - $BUILD_ID
  - report_fails
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/from-dockerfile/tests_image
timeout: 7200s
