steps:
- args:
  - builds
  - submit
  - .
  - --region
  - europe-west1
  - --config
  - cloudbuild/sub_run_tests_1.yaml
  - --async
  - --substitutions
  - _BUCKET_DIR_NAME=$BUILD_ID
  entrypoint: gcloud
  name: gcr.io/cloud-builders/gcloud
timeout: 7200s
