steps:
- args:
  - run.py
  - $PROJECT_ID
  - testing-$PROJECT_ID
  - $BUILD_ID
  - run_cypress
  - small_test.cy.js
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/testing/testing_image
timeout: 7200s
