steps:
- args:
  - run.py
  - $PROJECT_ID
  - testing_bucket
  - $BUILD_ID
  - run_cypress
  - exceptions/setup_submission/max_running.js
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/testing/testing-image
timeout: 7200s
