steps:
- args:
  - dummy
  dir: tests
  entrypoint: echo
  name: gcr.io/cloud-builders/gcloud
- args:
  - run.py
  - $PROJECT_ID
  - tests-$PROJECT_ID
  - $_BUCKET_DIR_NAME
  - run_cypress
  - exceptions/slash_command/max_this_running.js
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/testing/testing_image
- args:
  - run.py
  - $PROJECT_ID
  - tests-$PROJECT_ID
  - $_BUCKET_DIR_NAME
  - run_cypress
  - exceptions/slash_command/not_invited.js
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/testing/testing_image
- args:
  - run.py
  - $PROJECT_ID
  - tests-$PROJECT_ID
  - $_BUCKET_DIR_NAME
  - run_cypress
  - exceptions/vote_click/already_voted.js
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/testing/testing_image
- args:
  - run.py
  - $PROJECT_ID
  - tests-$PROJECT_ID
  - $_BUCKET_DIR_NAME
  - run_cypress
  - exceptions/vote_click/not_a_potential_voter.js
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/testing/testing_image
- args:
  - run.py
  - $PROJECT_ID
  - tests-$PROJECT_ID
  - $_BUCKET_DIR_NAME
  - run_cypress
  - exceptions/vote_submission/no_time_left.js
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/testing/testing_image
- args:
  - run.py
  - $PROJECT_ID
  - tests-$PROJECT_ID
  - $_BUCKET_DIR_NAME
  - run_cypress
  - special_characters.js
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/testing/testing_image
timeout: 3600s
