steps:
- args:
  - $_BUCKET_DIR_NAME
  dir: tests
  entrypoint: echo
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/from-dockerfile/tests_image
- args:
  - run.py
  - $PROJECT_ID
  - tests-$PROJECT_ID
  - $_BUCKET_DIR_NAME
  - run_cypress
  - exceptions/game_dead/open_view.cy.js
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/from-dockerfile/tests_image
- args:
  - run.py
  - $PROJECT_ID
  - tests-$PROJECT_ID
  - $_BUCKET_DIR_NAME
  - run_cypress
  - exceptions/game_dead/update_view.cy.js
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/from-dockerfile/tests_image
- args:
  - run.py
  - $PROJECT_ID
  - tests-$PROJECT_ID
  - $_BUCKET_DIR_NAME
  - run_cypress
  - exceptions/game_dead/view_response.cy.js
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/from-dockerfile/tests_image
- args:
  - run.py
  - $PROJECT_ID
  - tests-$PROJECT_ID
  - $_BUCKET_DIR_NAME
  - run_cypress
  - exceptions/guess_click/already_guessed.cy.js
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/from-dockerfile/tests_image
- args:
  - run.py
  - $PROJECT_ID
  - tests-$PROJECT_ID
  - $_BUCKET_DIR_NAME
  - run_cypress
  - exceptions/guess_click/organizer.cy.js
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/from-dockerfile/tests_image
- args:
  - run.py
  - $PROJECT_ID
  - tests-$PROJECT_ID
  - $_BUCKET_DIR_NAME
  - run_cypress
  - exceptions/guess_submission/max_these_guessers.cy.js
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/from-dockerfile/tests_image
- args:
  - run.py
  - $PROJECT_ID
  - tests-$PROJECT_ID
  - $_BUCKET_DIR_NAME
  - run_cypress
  - exceptions/guess_submission/no_time_left.cy.js
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/from-dockerfile/tests_image
- args:
  - run.py
  - $PROJECT_ID
  - tests-$PROJECT_ID
  - $_BUCKET_DIR_NAME
  - run_cypress
  - exceptions/pick_submission/not_between.cy.js
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/from-dockerfile/tests_image
- args:
  - run.py
  - $PROJECT_ID
  - tests-$PROJECT_ID
  - $_BUCKET_DIR_NAME
  - run_cypress
  - exceptions/pick_submission/not_integer.cy.js
  dir: tests
  entrypoint: python
  name: europe-west1-docker.pkg.dev/$PROJECT_ID/from-dockerfile/tests_image
timeout: 3600s
