local_function_file = 'local_function_{port}.txt'
cloud_deploy_function_file = 'cloud_deploy_function_{port}.txt'
pubsub_data_dir = 'data_dir'
cypress_screenshots_dir = 'cypress/screenshots'
cypress_videos_dir = 'cypress/videos'
sub_cypress_cloudbuild_file = 'cloudbuild/sub_cypress_{i}.yaml'
